export const cities = [
  'București',
  'Cluj-Napoca',
  'Timișoara',
  'Iași',
  'Constanța',
  'Craiova',
  'Brașov',
  'Galați',
  'Ploiești',
  'Oradea',
  'Brăila',
  'Arad',
  'Pitești',
  'Sibiu',
  'Bacău',
  'Târgu Mureș',
  'Baia Mare',
  'Buzău',
  'Botoșani',
  'Satu Mare',
  'Râmnicu Vâlcea',
  'Drobeta-Turnu Severin',
  'Suceava',
  'Piatra Neamț',
  'Târgu Jiu',
  'Târgoviște',
  'Focșani',
  'Bistrița',
  'Reșița',
  'Tulcea',
  'Slatina',
  'Călărași',
  'Alba Iulia',
  'Giurgiu',
  'Deva',
  'Hunedoara',
  'Zalău',
  'Sfântu Gheorghe',
  'Bârlad',
  'Vaslui',
  'Roman',
  'Slobozia',
  'Turda',
  'Mediaș',
  'Alexandria',
  'Voluntari',
  'Lugoj',
  'Medgidia',
  'Onești',
  'Sighetu Marmației',
  'Petroșani',
  'Mangalia',
  'Tecuci',
  'Odorheiu Secuiesc',
  'Râmnicu Sărat',
  'Pașcani',
  'Dej',
  'Reghin',
  'Năvodari',
  'Câmpina',
  'Mioveni',
  'Câmpulung',
  'Caracal',
  'Săcele',
  'Făgăraș',
  'Fetești',
  'Sighișoara',
  'Borșa',
  'Roșiorii de Vede',
  'Curtea de Argeș',
  'Sebeș',
  'Huși',
  'Fălticeni',
  'Pantelimon',
  'Oltenița',
  'Turnu Măgurele',
  'Caransebeș',
  'Dorohoi',
  'Vulcan',
  'Rădăuți',
  'Zărnești',
  'Lupeni',
  'Aiud',
  'Petrila',
  'Câmpia Turzii',
  'Buftea',
  'Târnăveni',
  'Moinești',
  'Codlea',
  'Cugir',
  'Carei',
  'Gherla',
  'Blaj',
  'Comănești',
  'Motru',
  'Târgu Neamț',
  'Moreni',
  'Târgu Secuiesc',
  'Gheorgheni',
  'Orăștie',
  'Balș',
  'Băicoi',
  'Drăgășani',
  'Salonta',
  'Băilești',
  'Calafat',
  'Cernavodă',
  'Filiași',
  'Câmpulung Moldovenesc',
  'Corabia',
  'Adjud',
  'Breaza',
  'Bocșa',
  'Marghita',
  'Baia Sprie',
  'Bragadiru',
  'Luduș',
  'Urziceni',
  'Vișeu de Sus',
  'Râșnov',
  'Buhuși',
  'Ștefănești',
  'Brad',
  'Vatra Dornei',
  'Cisnădie',
  'Mizil',
  'Pucioasa',
  'Chitila',
  'Zimnicea',
  'Toplița',
  'Otopeni',
  'Ovidiu',
  'Gura Humorului',
  'Găești',
  'Vicovu de Sus',
  'Țăndărei',
  'Ocna Mureș',
  'Bolintin-Vale',
  'Avrig',
  'Pecica',
  'Simeria',
  'Moldova Nouă',
  'Sânnicolau Mare',
  'Vălenii de Munte',
  'Dăbuleni',
  'Comarnic',
  'Negrești-Oaș',
  'Rovinari',
  'Scornicești',
  'Târgu Lăpuș',
  'Săcueni',
  'Videle',
  'Sântana',
  'Oravița',
  'Târgu Ocna',
  'Călan',
  'Boldești-Scăeni',
  'Măgurele',
  'Hârlău',
  'Drăgănești-Olt',
  'Jimbolia',
  'Mărășești',
  'Beiuș',
  'Beclean',
  'Urlați',
  'Oțelu Roșu',
  'Strehaia',
  'Târgu Frumos',
  'Orșova',
  'Sinaia',
  'Jibou',
  'Sovata',
  'Costești',
  'Ianca',
  'Lipova',
  'Dolhasca',
  'Topoloveni',
  'Murfatlar',
  'Nehoiu',
  'Flămânzi',
  'Covasna',
  'Aleșd',
  'Valea lui Mihai',
  'Darabani',
  'Hațeg',
  'Sângeorz-Băi',
  'Titu',
  'Cristuru Secuiesc',
  'Hârșova',
  'Liteni',
  'Năsăud',
  'Podu Iloaiei',
  'Eforie',
  'Odobești',
  'Huedin',
  'Ineu',
  'Salcea',
  'Seini',
  'Uricani',
  'Babadag',
  'Bumbești-Jiu',
  'Bușteni',
  'Agnita',
  'Iernut',
  'Baraolt',
  'Tășnad',
  'Roznov',
  'Băbeni',
  'Negrești',
  'Recaș',
  'Măcin',
  'Târgu Cărbunești',
  'Chișineu-Criș',
  'Siret',
  'Mihăilești',
  'Budești',
  'Plopeni',
  'Panciu',
  'Călimănești',
  'Fieni',
  'Șomcuta Mare',
  'Întorsura Buzăului',
  'Zlatna',
  'Anina',
  'Curtici',
  'Nădlac',
  'Dumbrăveni',
  'Victoria',
  'Amara',
  'Pătârlagele',
  'Techirghiol',
  'Pogoanele',
  'Ulmeni',
  'Turceni',
  'Câmpeni',
  'Cehu Silvaniei',
  'Tăuții-Măgherăuș',
  'Murgeni',
  'Tismana',
  'Buziaș',
  'Segarcea',
  'Săveni',
  'Pâncota',
  'Ungheni',
  'Sărmașu',
  'Răcari',
  'Tălmaciu',
  'Cajvana',
  'Vlăhița',
  'Fundulea',
  'Livada',
  'Făget',
  'Teiuș',
  'Bicaz',
  'Ștei',
  'Însurăței',
  'Lehliu Gară',
  'Târgu Bujor',
  'Piatra-Olt',
  'Horezu',
  'Deta',
  'Ardud',
  'Bălan',
  'Slănic',
  'Brezoi',
  'Potcoava',
  'Gătaia',
  'Novaci',
  'Miercurea Nirajului',
  'Copșa Mică',
  'Băile Herculane',
  'Ghimbav',
  'Baneasa',
  'Sângeorgiu de Pădure',
  'Isaccea',
  'Abrud',
  'Fierbinți-Târg',
  'Săliște',
  'Frasin',
  'Cavnic',
  'Săliștea de Sus',
  'Băile Olănești',
  'Berbești',
  'Predeal',
  'Azuga',
  'Aninoasa',
  'Bucecea',
  'Slănic-Moldova',
  'Milișăuți',
  'Baia de Aramă',
  'Făurei',
  'Vânju Mare',
  'Chineju',
  'Eforie Nord',
  'Eforie Sud',
  'Costinesti',
  'Vama Veche',
];
